import { getService, money, type StateCode } from "@/lib/capability";

export type LedgerItem = {
  id: string;
  kind: "application" | "payment" | "notice";
  title: string;
  status: "Action needed" | "In progress" | "Complete" | "Payment pending";
  updated: string;
  nextAction: string;
  amount?: number;
};

export const seededLedger: LedgerItem[] = [
  { id: "RAAH-APP-2048", kind: "application", title: "Change address on driving licence", status: "Action needed", updated: "Today, 10:42", nextAction: "Add your new address proof" },
  { id: "RAAH-APP-2047", kind: "application", title: "Remove loan from vehicle record", status: "In progress", updated: "Yesterday", nextAction: "We are checking Form 35", amount: 13500 },
  { id: "RAAH-PAY-0908", kind: "payment", title: "Address change payment", status: "Payment pending", updated: "22 Aug, 14:18", nextAction: "We will reconcile this automatically within 30 minutes", amount: 23000 },
  { id: "RAAH-NOTICE-0001", kind: "notice", title: "Document check reminder", status: "Complete", updated: "21 Aug", nextAction: "This notice is verified and was generated by Raah" }
];

export function verifiedReference(ref: string) {
  return seededLedger.find((item) => item.id.toLowerCase() === ref.trim().toLowerCase());
}

export function createApplication(serviceId: string, state: StateCode) {
  const service = getService(serviceId);
  const suffix = String(Math.floor(1000 + Math.random() * 8999));
  return {
    id: `RAAH-APP-${suffix}`,
    title: service?.title ?? "Road transport service",
    state,
    status: "Ready for review",
    fee: money(serviceId === "challan" ? 50000 : serviceId === "record-correction" ? 0 : serviceId === "hypothecation-removal" ? 13500 : 23000),
    nextAction: "Review your answers. Payment is the final step."
  };
}
